### PR TITLE
Fix post-link.sh when PREFIX contains a space

### PR DESCRIPTION
**Pull request by tsibley**
While $PREFIX itself was always quoted here, the eval-ed contents of gdk-pixbuf-2.0.pc were not properly handled.  The value of PREFIX ends up in the pkg-config file, so the eval was busted when PREFIX contained a space.  The selected pkg-config lines need quoting to adapt them for the shell as variables in pkg-config's syntax are line-delimited not word-delimited.

Note that the basic grep that remains here will also incorrectly omit variables whose value contains a colon, but this is probably less likely in general.  It could be fixed, however, by using a more nuanced grep pattern.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by tsibley** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
Thanks for chipping away at this. Do you think it would be better to use `pkg-config --variable=...` to try to avoid some of the grep/sed gymnastics? I don't have a problem with the current approach but I think that might avoid some of the further robustness issues you mentioned. Getting rid of the `eval` would make me feel better.

**Comment by pkgw** [comment]
Actually, I'm going to strengthen my comment and say that I think we should be using `pkg-config --variable=` here, unless you can see a compelling reason not to.

**Comment by tsibley** [comment]
Yeah, `pkg-config` is definitely the right tool for the job. I didn't use it because of the comment at the top of `post-link.sh` (from its inception):

https://github.com/conda-forge/gdk-pixbuf-feedstock/blob/c505fd062f4ec5b9d253a0b55c7ffb48bc3bc7e6/recipe/post-link.sh#L3-L5

Not clear from the introducing commit fe85f46d88e2c13287006c5cfdcdd8ca69e651ca why `pkg-config` is avoided, but my presumption is that while the `.pc` file might be available in the Conda environment, the `pkg-config` command may not always be? I don't know enough about the intricacies of Conda dependencies to know if that's the case without some testing.

**Comment by tsibley** [comment]
Right, so in a quick test where I install `gdk-pixbuf` into a fresh Conda prefix, there's no `bin/pkg-config`, which means it's dependent on the host system to have it installed, which can't be relied upon (esp. cross platform?).

What about if `post-link.sh` uses `pkg-config` if it's available, but otherwise falls back to the hacky `grep`/`sed`/`eval`?

**Comment by tsibley** [comment]
Actually, why is `post-link.sh` finding the path to the loaders cache file itself? The Windows version, `post-link.bat`, calls `gdk-pixbuf-queryloaders` with the `--update-cache` argument instead of specifying an explicit path. This presumably uses the compiled-in path that the shell script goes thru pains to extract from the pkg-config data.

**Comment by tsibley** [comment]
Pushed 53d00b8 to use `--update-cache` instead.

**Comment by pkgw** [comment]
Duh, it helps if I actually read the source code. I wrote that helpful comment myself 4+ years ago explaining exactly why the `--variable` approach was wrong! Thank you once again for being careful with this.

**Comment by tsibley** [comment]
:raised_hands: Thanks for merging! :-)

**Pull request merged**
